---
# task file for Dgnest.Ntp

- name: Update package repositories
  become: true
  apt:
    update_cache: True
  when: ansible_distribution == "Ubuntu"

- name: Install ntp package dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  register: install_ntp_package_dependencies
  with_items: "{{ _ntp_package_dependencies | default([]) }}"
  when: _ntp_package_dependencies is defined

- name: Install ntp dependencies
  become: true
  apt:
    name: "{{ item.name }}"
    state: present
  register: install_ntp_dependencies
  with_items: "{{ _ntp_dependencies | default([]) }}"
  when: _ntp_dependencies is defined
