---
# environment file for Dgnest.Ntp

- name: Create files ntp
  sudo: yes
  file:
    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner }}"
  with_items: _ntp_create_files
  when: _ntp_create_files is defined
